### ISSUE TITLE
服务器返回的商品组  正常的商品里面本身就是缺少某个属性，然后运行就会崩溃，这个怎么解决

### ISSUE THREAD

**Issue by beibing8801** [SunriseOYR/SKUDataFilter#1]

**Comment by SunriseOYR** [comment]
新加入了condition 检测，过滤并提示了不完整的condition，重新下载，不会有问题了

**Comment by beibing8801** [comment]
我们这组正常的商品就是少一个属性  也是一个完整的商品。过滤掉的话就不能满足需求了。

**Comment by beibing8801** [comment]
怎么根据这个需求进行相应的逻辑调整，搞了一下午，还是没有实现，望指教一下

**Comment by SunriseOYR** [comment]
少一个属性就是不完整啊,  少一个属性，少的那个属性怎么算啊，是都可以选，还是怎么的，这个在正常的逻辑，属性少了肯定就是不满足条件，你可以根据需求在解析数据的时候，补齐他少的属性

**Comment by beibing8801** [comment]
好的，谢谢！
