### ISSUE TITLE
如何赋值 初始 选中 的索引

### ISSUE THREAD

**Issue by zp18862956943** [SunriseOYR/SKUDataFilter#2]
很好用，不知道是否可以支持一进去 就赋值 我想 选中的 索引数组？有些情况 初始 就有 值了，能否帮助一下

**Comment by SunriseOYR** [comment]
周末 试试

**Comment by SunriseOYR** [comment]
我这个 可以默认选中第一组 ，这个满足不了你的需求吗

**Comment by zp18862956943** [comment]
不好意思 ， 之前忘记看了，现在我的做法 是 在你的代码里 传了一个值，继而 通过 model.result 与 那个 值比较 ，赋值 _defaultSku。不知道有没有更好的办法

**Comment by SunriseOYR** [comment]
_filter.needDefaultValue = YES; 只需要这样写就可以了，拿到数据的时候更新UI
