### ISSUE TITLE
数据顺序如果不一致要怎么处理

### ISSUE THREAD

**Issue by DNC-7** [SunriseOYR/SKUDataFilter#3]
作者你好，在使用过程中，出现了property和condition顺序不一致的情况，也就是你在使用注意事项第二点提到的。现在遇到了这种情况，请问该怎么解决？

**Comment by SunriseOYR** [comment]
这个需要你 在解析数据的时候， 调整一下，或者喊后台修改

**Comment by DNC-7** [comment]
> 这个需要你 在解析数据的时候， 调整一下，或者喊后台修改

恩恩，后来自己重新排序了一下解决了
