### ISSUE TITLE
如何赋值初始选中的索引

### ISSUE THREAD

**Issue by deanli08** [SunriseOYR/SKUDataFilter#4]
作者您好：比如我在商品详情界面选中了属性，然后在购物车里面去修改这个属性的时候，弹出界面的时候希望能自动选中已经选中的属性，但这个属性不是第一个，这样应该怎么实现？

**Comment by deanli08** [comment]
@SunriseOYR 希望可以给个解决方案

**Comment by SunriseOYR** [comment]
暂时 你先 把属性选中的indexPath 记录一下， 然后 遍历调用一下 didSelectedPropertyWithIndexPath:
最后刷新下 UI ,我后面更新下接口

**Comment by TML007** [comment]
> 

同上，不知道到作者还继续更新维护不
