### ISSUE TITLE
condition不完整

### ISSUE THREAD

**Issue by MoDaBao** [SunriseOYR/SKUDataFilter#5]
condition不完整是因为数据排序不对吗

**Comment by SunriseOYR** [comment]
不完整 是因为 某条sku中的属性， 和总的属性种类 不相等
如 颜色、大小、样式
sku 只有 颜色 大小
就称为不完整， 这个就需要自己去补全了

**Comment by MoDaBao** [comment]
感谢感谢，找到原因了，我遇到的不完整是因为条件的顺序跟规格的顺序不一致导致的，现在解决了
